# DATA UNDERSTANDING

The purpose of this notebook is to understand the structure and quality of the marketing campaign dataset before performing statistical analysis and machine learning.

This stage includes:

* Data loading
* Data cleaning
* Missing value analysis
* Duplicate analysis
* Data type checking
* Initial feature engineering
* Dataset merging

In [ ]:
# import thư viện
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# file control_group.csv 
control_df = pd.read_csv('../data/raw/control_group.csv', sep=';')
control_df.head()

,Campaign Name,Date,Spend [USD],# of Impressions,Reach,# of Website Clicks,# of Searches,# of View Content,# of Add to Cart,# of Purchase
0,Control Campaign,1.08.2019,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0
1,Control Campaign,2.08.2019,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0
2,Control Campaign,3.08.2019,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0
3,Control Campaign,4.08.2019,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0
4,Control Campaign,5.08.2019,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# file test_group.csv
test_df = pd.read_csv('../data/raw/test_group.csv', sep=';')
test_df.head()

,Campaign Name,Date,Spend [USD],# of Impressions,Reach,# of Website Clicks,# of Searches,# of View Content,# of Add to Cart,# of Purchase
0,Test Campaign,1.08.2019,3008,39550,35820,3038,1946,1069,894,255
1,Test Campaign,2.08.2019,2542,100719,91236,4657,2359,1548,879,677
2,Test Campaign,3.08.2019,2365,70263,45198,7885,2572,2367,1268,578
3,Test Campaign,4.08.2019,2710,78451,25937,4216,2216,1437,566,340
4,Test Campaign,5.08.2019,2297,114295,95138,5863,2106,858,956,768

In [4]:
control_df.isnull().sum()

Campaign Name          0
Date                   0
Spend [USD]            0
# of Impressions       1
Reach                  1
# of Website Clicks    1
# of Searches          1
# of View Content      1
# of Add to Cart       1
# of Purchase          1
dtype: int64

In [5]:
test_df.isnull().sum()

Campaign Name          0
Date                   0
Spend [USD]            0
# of Impressions       0
Reach                  0
# of Website Clicks    0
# of Searches          0
# of View Content      0
# of Add to Cart       0
# of Purchase          0
dtype: int64

In [6]:
# kiểm tra kích thước của hai DataSet
print(control_df.shape)
print(test_df.shape)

(30, 10)
(30, 10)

In [7]:
control_df.info()
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     str
 1   Date                 30 non-null     str
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     29 non-null     float64
 4   Reach                29 non-null     float64
 5   # of Website Clicks  29 non-null     float64
 6   # of Searches        29 non-null     float64
 7   # of View Content    29 non-null     float64
 8   # of Add to Cart     29 non-null     float64
 9   # of Purchase        29 non-null     float64
dtypes: float64(7), int64(1), str(2)
memory usage: 3.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     str
 1   Date                 30 non-null     str
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     30 non-null     int64
 4   Reach                30 non-null     int64
 5   # of Website Clicks  30 non-null     int64
 6   # of Searches        30 non-null     int64
 7   # of View Content    30 non-null     int64
 8   # of Add to Cart     30 non-null     int64
 9   # of Purchase        30 non-null     int64
dtypes: int64(8), str(2)
memory usage: 3.1 KB

In [8]:
control_df.duplicated().sum()
test_df.duplicated().sum()

np.int64(0)

In [9]:
control_df.describe()
test_df.describe()

,Spend [USD],# of Impressions,Reach,# of Website Clicks,# of Searches,# of View Content,# of Add to Cart,# of Purchase
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2563.066667,74584.800000,53491.566667,6032.333333,2418.966667,1858.000000,881.533333,521.233333
std,348.687681,32121.377422,28795.775752,1708.567263,388.742312,597.654669,347.584248,211.047745
min,1968.000000,22521.000000,10598.000000,3038.000000,1854.000000,858.000000,278.000000,238.000000
25%,2324.500000,47541.250000,31516.250000,4407.000000,2043.000000,1320.000000,582.500000,298.000000
50%,2584.000000,68853.500000,44219.500000,6242.500000,2395.500000,1881.000000,974.000000,500.000000
75%,2836.250000,99500.000000,78778.750000,7604.750000,2801.250000,2412.000000,1148.500000,701.000000
max,3112.000000,133771.000000,109834.000000,8264.000000,2978.000000,2801.000000,1391.000000,890.000000

In [10]:
new_columns = [
    'campaign_name',
    'date',
    'spend_usd',
    'impressions',
    'reach',
    'website_clicks',
    'searches',
    'view_content',
    'add_to_cart',
    'purchase'
]

control_df.columns = new_columns
test_df.columns = new_columns

In [11]:
control_df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase
0,Control Campaign,1.08.2019,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0
1,Control Campaign,2.08.2019,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0
2,Control Campaign,3.08.2019,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0
3,Control Campaign,4.08.2019,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0
4,Control Campaign,5.08.2019,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
test_df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase
0,Test Campaign,1.08.2019,3008,39550,35820,3038,1946,1069,894,255
1,Test Campaign,2.08.2019,2542,100719,91236,4657,2359,1548,879,677
2,Test Campaign,3.08.2019,2365,70263,45198,7885,2572,2367,1268,578
3,Test Campaign,4.08.2019,2710,78451,25937,4216,2216,1437,566,340
4,Test Campaign,5.08.2019,2297,114295,95138,5863,2106,858,956,768

In [13]:
control_df['group'] = 'control'
test_df['group'] = 'test'

In [14]:
control_df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase,group
0,Control Campaign,1.08.2019,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0,control
1,Control Campaign,2.08.2019,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0,control
2,Control Campaign,3.08.2019,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0,control
3,Control Campaign,4.08.2019,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0,control
4,Control Campaign,5.08.2019,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,control

In [15]:
test_df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase,group
0,Test Campaign,1.08.2019,3008,39550,35820,3038,1946,1069,894,255,test
1,Test Campaign,2.08.2019,2542,100719,91236,4657,2359,1548,879,677,test
2,Test Campaign,3.08.2019,2365,70263,45198,7885,2572,2367,1268,578,test
3,Test Campaign,4.08.2019,2710,78451,25937,4216,2216,1437,566,340,test
4,Test Campaign,5.08.2019,2297,114295,95138,5863,2106,858,956,768,test

In [16]:
df = pd.concat([control_df, test_df])

In [17]:
df.reset_index(drop=True, inplace=True)

In [18]:
df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase,group
0,Control Campaign,1.08.2019,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0,control
1,Control Campaign,2.08.2019,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0,control
2,Control Campaign,3.08.2019,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0,control
3,Control Campaign,4.08.2019,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0,control
4,Control Campaign,5.08.2019,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,control

In [19]:
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (60, 11)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_name   60 non-null     str
 1   date            60 non-null     str
 2   spend_usd       60 non-null     int64
 3   impressions     59 non-null     float64
 4   reach           59 non-null     float64
 5   website_clicks  59 non-null     float64
 6   searches        59 non-null     float64
 7   view_content    59 non-null     float64
 8   add_to_cart     59 non-null     float64
 9   purchase        59 non-null     float64
 10  group           60 non-null     str
dtypes: float64(7), int64(1), str(3)
memory usage: 7.0 KB

In [21]:
df.isnull().sum()

campaign_name     0
date              0
spend_usd         0
impressions       1
reach             1
website_clicks    1
searches          1
view_content      1
add_to_cart       1
purchase          1
group             0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df['date'] = pd.to_datetime(
    df['date'],
    format='%d.%m.%Y'
)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_name   60 non-null     str
 1   date            60 non-null     datetime64[us]
 2   spend_usd       60 non-null     int64
 3   impressions     59 non-null     float64
 4   reach           59 non-null     float64
 5   website_clicks  59 non-null     float64
 6   searches        59 non-null     float64
 7   view_content    59 non-null     float64
 8   add_to_cart     59 non-null     float64
 9   purchase        59 non-null     float64
 10  group           60 non-null     str
dtypes: datetime64[us](1), float64(7), int64(1), str(2)
memory usage: 6.5 KB

In [25]:
df.dtypes

campaign_name                str
date              datetime64[us]
spend_usd                  int64
impressions              float64
reach                    float64
website_clicks           float64
searches                 float64
view_content             float64
add_to_cart              float64
purchase                 float64
group                        str
dtype: object

In [26]:
df.describe()

,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase
count,60,60.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,2019-08-15 12:00:00,2425.750000,91775.881356,70868.644068,5682.593220,2321.813559,1900.169492,1087.220339,522.000000
min,2019-08-01 00:00:00,1757.000000,22521.000000,10598.000000,2277.000000,1001.000000,848.000000,278.000000,222.000000
25%,2019-08-08 00:00:00,2073.750000,68853.500000,43230.000000,4227.500000,1962.500000,1249.000000,848.500000,340.000000
50%,2019-08-15 12:00:00,2420.500000,95843.000000,76219.000000,5691.000000,2390.000000,1975.000000,1075.000000,501.000000
75%,2019-08-23 00:00:00,2727.500000,117315.000000,95490.500000,7218.500000,2778.500000,2424.000000,1386.500000,693.000000
max,2019-08-30 00:00:00,3112.000000,145248.000000,127852.000000,8264.000000,4891.000000,4219.000000,1913.000000,890.000000
std,NaN,381.130461,32465.070636,31023.653515,1754.777559,669.040576,687.263844,430.205246,196.973917

In [27]:
df.sample(5)

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase,group
29,Control Campaign,2019-08-30,2324,111306.0,88632.0,4658.0,1615.0,1249.0,442.0,670.0,control
27,Control Campaign,2019-08-28,2421,141654.0,125874.0,6287.0,1672.0,1589.0,1711.0,643.0,control
45,Test Campaign,2019-08-16,3076,106584.0,81389.0,6800.0,2661.0,2594.0,1059.0,487.0,test
11,Control Campaign,2019-08-12,2319,116639.0,100189.0,2993.0,1397.0,1147.0,1439.0,794.0,control
52,Test Campaign,2019-08-23,2407,60286.0,49329.0,5077.0,2592.0,2004.0,632.0,473.0,test

In [28]:
# Save at processed data
df.to_csv(
    '../data/processed/cleaned_marketing.csv',
    index=False
)

In [29]:
# Check for saved file
saved_df = pd.read_csv(
    '../data/processed/cleaned_marketing.csv'
)

saved_df.head()

,campaign_name,date,spend_usd,impressions,reach,website_clicks,searches,view_content,add_to_cart,purchase,group
0,Control Campaign,2019-08-01,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0,control
1,Control Campaign,2019-08-02,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0,control
2,Control Campaign,2019-08-03,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0,control
3,Control Campaign,2019-08-04,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0,control
4,Control Campaign,2019-08-05,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,control