In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler

In [7]:
# file control_group.csv 
control_df = pd.read_csv('../data/raw/control_group.csv', sep=';')
control_df.head()

      Campaign Name       Date  ...  # of Add to Cart  # of Purchase
0  Control Campaign  1.08.2019  ...            1819.0          618.0
1  Control Campaign  2.08.2019  ...            1219.0          511.0
2  Control Campaign  3.08.2019  ...            1134.0          372.0
3  Control Campaign  4.08.2019  ...            1183.0          340.0
4  Control Campaign  5.08.2019  ...               NaN            NaN

[5 rows x 10 columns]

In [8]:
# file test_group.csv
test_df = pd.read_csv('../data/raw/test_group.csv', sep=';')
test_df.head()

   Campaign Name       Date  ...  # of Add to Cart  # of Purchase
0  Test Campaign  1.08.2019  ...               894            255
1  Test Campaign  2.08.2019  ...               879            677
2  Test Campaign  3.08.2019  ...              1268            578
3  Test Campaign  4.08.2019  ...               566            340
4  Test Campaign  5.08.2019  ...               956            768

[5 rows x 10 columns]

In [10]:
control_df.isnull().sum()

Campaign Name          0
Date                   0
Spend [USD]            0
# of Impressions       1
Reach                  1
# of Website Clicks    1
# of Searches          1
# of View Content      1
# of Add to Cart       1
# of Purchase          1
dtype: int64

In [11]:
test_df.isnull().sum()

Campaign Name          0
Date                   0
Spend [USD]            0
# of Impressions       0
Reach                  0
# of Website Clicks    0
# of Searches          0
# of View Content      0
# of Add to Cart       0
# of Purchase          0
dtype: int64

In [ ]:
# kiểm tra kích thước của hai DataSet
print(control_df.shape)
print(test_df.shape)

(30, 10)
(30, 10)

In [13]:
control_df.info()
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     str
 1   Date                 30 non-null     str
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     29 non-null     float64
 4   Reach                29 non-null     float64
 5   # of Website Clicks  29 non-null     float64
 6   # of Searches        29 non-null     float64
 7   # of View Content    29 non-null     float64
 8   # of Add to Cart     29 non-null     float64
 9   # of Purchase        29 non-null     float64
dtypes: float64(7), int64(1), str(2)
memory usage: 3.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign Name        30 non-null     str
 1   Date                 30 non-null     str
 2   Spend [USD]          30 non-null     int64
 3   # of Impressions     30 non-null     int64
 4   Reach                30 non-null     int64
 5   # of Website Clicks  30 non-null     int64
 6   # of Searches        30 non-null     int64
 7   # of View Content    30 non-null     int64
 8   # of Add to Cart     30 non-null     int64
 9   # of Purchase        30 non-null     int64
dtypes: int64(8), str(2)
memory usage: 3.1 KB

In [14]:
control_df.duplicated().sum()
test_df.duplicated().sum()

np.int64(0)

In [15]:
control_df.describe()
test_df.describe()

       Spend [USD]  # of Impressions  ...  # of Add to Cart  # of Purchase
count    30.000000         30.000000  ...         30.000000      30.000000
mean   2563.066667      74584.800000  ...        881.533333     521.233333
std     348.687681      32121.377422  ...        347.584248     211.047745
min    1968.000000      22521.000000  ...        278.000000     238.000000
25%    2324.500000      47541.250000  ...        582.500000     298.000000
50%    2584.000000      68853.500000  ...        974.000000     500.000000
75%    2836.250000      99500.000000  ...       1148.500000     701.000000
max    3112.000000     133771.000000  ...       1391.000000     890.000000

[8 rows x 8 columns]

In [16]:
new_columns = [
    'campaign_name',
    'date',
    'spend_usd',
    'impressions',
    'reach',
    'website_clicks',
    'searches',
    'view_content',
    'add_to_cart',
    'purchase'
]

control_df.columns = new_columns
test_df.columns = new_columns

In [17]:
control_df.head()

      campaign_name       date  spend_usd  ...  view_content  add_to_cart  purchase
0  Control Campaign  1.08.2019       2280  ...        2159.0       1819.0     618.0
1  Control Campaign  2.08.2019       1757  ...        1841.0       1219.0     511.0
2  Control Campaign  3.08.2019       2343  ...        1549.0       1134.0     372.0
3  Control Campaign  4.08.2019       1940  ...         982.0       1183.0     340.0
4  Control Campaign  5.08.2019       1835  ...           NaN          NaN       NaN

[5 rows x 10 columns]

In [18]:
test_df.head()

   campaign_name       date  spend_usd  ...  view_content  add_to_cart  purchase
0  Test Campaign  1.08.2019       3008  ...          1069          894       255
1  Test Campaign  2.08.2019       2542  ...          1548          879       677
2  Test Campaign  3.08.2019       2365  ...          2367         1268       578
3  Test Campaign  4.08.2019       2710  ...          1437          566       340
4  Test Campaign  5.08.2019       2297  ...           858          956       768

[5 rows x 10 columns]

In [19]:
control_df['group'] = 'control'
test_df['group'] = 'test'

In [20]:
control_df.head()

      campaign_name       date  spend_usd  ...  add_to_cart  purchase    group
0  Control Campaign  1.08.2019       2280  ...       1819.0     618.0  control
1  Control Campaign  2.08.2019       1757  ...       1219.0     511.0  control
2  Control Campaign  3.08.2019       2343  ...       1134.0     372.0  control
3  Control Campaign  4.08.2019       1940  ...       1183.0     340.0  control
4  Control Campaign  5.08.2019       1835  ...          NaN       NaN  control

[5 rows x 11 columns]

In [21]:
test_df.head()

   campaign_name       date  spend_usd  ...  add_to_cart  purchase  group
0  Test Campaign  1.08.2019       3008  ...          894       255   test
1  Test Campaign  2.08.2019       2542  ...          879       677   test
2  Test Campaign  3.08.2019       2365  ...         1268       578   test
3  Test Campaign  4.08.2019       2710  ...          566       340   test
4  Test Campaign  5.08.2019       2297  ...          956       768   test

[5 rows x 11 columns]

In [22]:
df = pd.concat([control_df, test_df])

In [23]:
df.reset_index(drop=True, inplace=True)

In [24]:
df.head()

      campaign_name       date  spend_usd  ...  add_to_cart  purchase    group
0  Control Campaign  1.08.2019       2280  ...       1819.0     618.0  control
1  Control Campaign  2.08.2019       1757  ...       1219.0     511.0  control
2  Control Campaign  3.08.2019       2343  ...       1134.0     372.0  control
3  Control Campaign  4.08.2019       1940  ...       1183.0     340.0  control
4  Control Campaign  5.08.2019       1835  ...          NaN       NaN  control

[5 rows x 11 columns]

In [25]:
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (60, 11)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_name   60 non-null     str
 1   date            60 non-null     str
 2   spend_usd       60 non-null     int64
 3   impressions     59 non-null     float64
 4   reach           59 non-null     float64
 5   website_clicks  59 non-null     float64
 6   searches        59 non-null     float64
 7   view_content    59 non-null     float64
 8   add_to_cart     59 non-null     float64
 9   purchase        59 non-null     float64
 10  group           60 non-null     str
dtypes: float64(7), int64(1), str(3)
memory usage: 7.0 KB

In [27]:
df.isnull().sum()

campaign_name     0
date              0
spend_usd         0
impressions       1
reach             1
website_clicks    1
searches          1
view_content      1
add_to_cart       1
purchase          1
group             0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [30]:
df['date'] = pd.to_datetime(
    df['date'],
    format='%d.%m.%Y'
)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_name   60 non-null     str
 1   date            60 non-null     datetime64[us]
 2   spend_usd       60 non-null     int64
 3   impressions     59 non-null     float64
 4   reach           59 non-null     float64
 5   website_clicks  59 non-null     float64
 6   searches        59 non-null     float64
 7   view_content    59 non-null     float64
 8   add_to_cart     59 non-null     float64
 9   purchase        59 non-null     float64
 10  group           60 non-null     str
dtypes: datetime64[us](1), float64(7), int64(1), str(2)
memory usage: 6.5 KB

In [32]:
df.dtypes

campaign_name                str
date              datetime64[us]
spend_usd                  int64
impressions              float64
reach                    float64
website_clicks           float64
searches                 float64
view_content             float64
add_to_cart              float64
purchase                 float64
group                        str
dtype: object

In [33]:
df.describe()

                      date    spend_usd  ...  add_to_cart    purchase
count                   60    60.000000  ...    59.000000   59.000000
mean   2019-08-15 12:00:00  2425.750000  ...  1087.220339  522.000000
min    2019-08-01 00:00:00  1757.000000  ...   278.000000  222.000000
25%    2019-08-08 00:00:00  2073.750000  ...   848.500000  340.000000
50%    2019-08-15 12:00:00  2420.500000  ...  1075.000000  501.000000
75%    2019-08-23 00:00:00  2727.500000  ...  1386.500000  693.000000
max    2019-08-30 00:00:00  3112.000000  ...  1913.000000  890.000000
std                    NaN   381.130461  ...   430.205246  196.973917

[8 rows x 9 columns]

In [34]:
df.sample(5)

       campaign_name       date  spend_usd  ...  add_to_cart  purchase    group
3   Control Campaign 2019-08-04       1940  ...       1183.0     340.0  control
20  Control Campaign 2019-08-21       1803  ...       1460.0     800.0  control
27  Control Campaign 2019-08-28       2421  ...       1711.0     643.0  control
30     Test Campaign 2019-08-01       3008  ...        894.0     255.0     test
58     Test Campaign 2019-08-29       2805  ...       1168.0     677.0     test

[5 rows x 11 columns]

In [ ]:
# Save at processed data
df.to_csv(
    '../data/processed/cleaned_marketing.csv',
    index=False
)

In [ ]:
# Check for saved file
saved_df = pd.read_csv(
    '../data/processed/cleaned_marketing.csv'
)

saved_df.head()

      campaign_name        date  spend_usd  ...  add_to_cart  purchase    group
0  Control Campaign  2019-08-01       2280  ...       1819.0     618.0  control
1  Control Campaign  2019-08-02       1757  ...       1219.0     511.0  control
2  Control Campaign  2019-08-03       2343  ...       1134.0     372.0  control
3  Control Campaign  2019-08-04       1940  ...       1183.0     340.0  control
4  Control Campaign  2019-08-05       1835  ...          NaN       NaN  control

[5 rows x 11 columns]